#!/usr/bin/env bash

function setup_util_insomnium() (
	source "$DOROTHY/sources/bash.bash"

	# setup
	local options=(
		--app='Insomnium'
		--cli='insomnium'
		"$@"
		CASK='insomnium'
	)

	setup-util "${options[@]}"
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	setup_util_insomnium "$@"
fi
