#!/usr/bin/env bash

# https://github.com/direnv/direnv

function setup_util_direnv() (
	source "$DOROTHY/sources/bash.bash"

	# setup
	local arch options=(
		--cli='direnv'
		"$@"
		BREW='direnv'
	)

	setup-util "${options[@]}"
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	setup_util_direnv "$@"
fi
