#!/usr/bin/env bash

function setup_util_appcleaner() (
	source "$DOROTHY/sources/bash.bash"

	# improve performance for detectable utilities with conditional assets
	# if setup-util "$@" --check --cli=dust; then
	# 	return 0
	# fi

	# setup
	local options=(
		--app='AppCleaner'
		--cli='appcleaner'
		"$@"
		CASK='appcleaner'
	)

	setup-util "${options[@]}"
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	setup_util_appcleaner "$@"
fi
