#!/usr/bin/env bash

# https://github.com/direnv/direnv

function setup_util_direnv() (
	source "$DOROTHY/sources/bash.bash"

	# improve performance for detectable utilities with conditional assets
	# if setup-util "$@" --check --cli=dust; then
	# 	return 0
	# fi

	# setup
	local options=(
		--cli='direnv'
		"$@"
		BREW='direnv'
	)

	setup-util "${options[@]}"
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	setup_util_direnv "$@"
fi
