#!/usr/bin/env bash

# https://pkgs.tailscale.com/stable/

function setup_util_tailscale() (
	source "$DOROTHY/sources/bash.bash"

	# setup
	local options=(
		--app='Tailscale'
		--cli='tailscale'
		"$@"
		CASK='tailscale'
	)

	setup-util "${options[@]}"
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	setup_util_tailscale "$@"
fi
