#!/usr/bin/env bash

# https://github.com/obsidianmd/obsidian-releases

function setup_util_obsidian() (
	source "$DOROTHY/sources/bash.bash"

	# setup
	local options=(
		--app='Obsidian'
		--cli='obsidian'
		"$@"
		CASK='obsidian'
	)

	setup-util "${options[@]}"
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	setup_util_obsidian "$@"
fi
