#!/usr/bin/env bash

# https://github.com/x-motemen/ghq

function setup_util_ghq() (
	source "$DOROTHY/sources/bash.bash"

	# improve performance for detectable utilities with conditional assets
	if setup-util "$@" --check --cli=ghq; then
		return 0
	fi

	# setup
	local arch options=(
		--cli='ghq'
		"$@"
		BREW='ghq'
	)

	setup-util "${options[@]}"
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	setup_util_ghq "$@"
fi
